POST http://localhost:7000/locations
Content-Type: application/json

{
  "name": "Melbourne"
}

###

POST http://localhost:7000/rainfall
Content-Type: application/json

{
  "date": "7 Dec 2017",
  "amount": 9,
  "location": "5a24d668ef7ce0a8dbd08591"
}

###
GET http://localhost:7000/locations